apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-ivfd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-ivfd
    app.kubernetes.io/part-of: devfile-sample-go-basic-1
  name: devfile-sample-go-basic-ivfd
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-ivfd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-ivfd
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rsoaresd-tenant/devfile-sample-go-basic-1/devfile-sample-go-basic-ivfd@sha256:946e737ba1233b4933aefea2b460da6b166b42410dde2337d69e486e320d4466
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
